apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ixaris-app
spec:
  selector:
    matchLabels:
      app: ixaris-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ixaris-app
    spec:
      containers:
        - name: ixaris-app 
          image: butterlyextreme/ixaris:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
